// Correct station orders for each CTA L line, terminus to terminus.
// For lines that use the Loop, stations are listed in the order trains traverse them.

export const CTA_LINE_ORDERS: Record<string, string[]> = {
  Blue: [
    // O'Hare branch → subway → Congress branch
    "O'Hare Airport",
    "Rosemont",
    "Cumberland",
    "Harlem-O'Hare",
    "Jefferson Park",
    "Montrose-O'Hare",
    "Irving Park-O'Hare",
    "Addison-O'Hare",
    "Belmont-O'Hare",
    "Logan Square",
    "California/Milwaukee",
    "Western/Milwaukee",
    "Damen/Milwaukee",
    "Division/Milwaukee",
    "Chicago/Milwaukee",
    "Grand/Milwaukee",
    "Clark/Lake",
    "Washington/Dearborn",
    "Monroe/Dearborn",
    "Jackson/Dearborn",
    "LaSalle",
    "Clinton-Congress",
    "UIC-Halsted",
    "Racine",
    "Illinois Medical District",
    "Western-Congress",
    "Kedzie-Homan",
    "Pulaski-Congress",
    "Cicero-Congress",
    "Austin-Congress",
    "Oak Park-Congress",
    "Harlem-Congress",
    "Forest Park",
  ],

  Red: [
    "Howard",
    "Jarvis",
    "Morse",
    "Loyola",
    "Granville",
    "Thorndale",
    "Bryn Mawr",
    "Berwyn",
    "Argyle",
    "Lawrence",
    "Wilson",
    "Sheridan",
    "Addison-North Main",
    "Belmont-North Main",
    "Fullerton",
    "North/Clybourn",
    "Clark/Division",
    "Chicago/State",
    "Grand/State",
    "Lake/State",
    "Monroe/State",
    "Jackson/State",
    "Harrison",
    "Roosevelt/State",
    "Cermak-Chinatown",
    "Sox-35th-Dan Ryan",
    "47th-Dan Ryan",
    "Garfield-Dan Ryan",
    "63rd-Dan Ryan",
    "69th",
    "79th",
    "87th",
    "95th/Dan Ryan",
  ],

  Brown: [
    "Kimball",
    "Kedzie-Ravenswood",
    "Francisco",
    "Rockwell",
    "Western-Ravenswood",
    "Damen-Ravenswood",
    "Montrose-Ravenswood",
    "Irving Park-Ravenswood",
    "Addison-Ravenswood",
    "Paulina",
    "Southport",
    "Belmont-North Main",
    "Wellington",
    "Diversey",
    "Fullerton",
    "Armitage",
    "Sedgwick",
    "Chicago/Franklin",
    "Merchandise Mart",
    // Loop (outer track, counterclockwise)
    "Washington/Wells",
    "Quincy/Wells",
    "LaSalle/Van Buren",
    "Library",
    "Adams/Wabash",
    "Washington/Wabash",
    "State/Lake",
    "Clark/Lake",
  ],

  Purple: [
    "Linden",
    "Central-Evanston",
    "Noyes",
    "Foster",
    "Davis",
    "Dempster",
    "Main",
    "South Boulevard",
    "Howard",
    // Express runs Belmont–Howard; Purple Line shares with Brown south of Howard
    "Wilson",
    "Belmont-North Main",
    "Wellington",
    "Diversey",
    "Fullerton",
    "Armitage",
    "Sedgwick",
    "Chicago/Franklin",
    "Merchandise Mart",
    // Loop
    "Washington/Wells",
    "Quincy/Wells",
    "LaSalle/Van Buren",
    "Library",
    "Adams/Wabash",
    "Washington/Wabash",
    "State/Lake",
    "Clark/Lake",
  ],

  Orange: [
    "Midway Airport",
    "Pulaski-Midway",
    "Kedzie-Midway",
    "Western-Midway",
    "35th/Archer",
    "Ashland-Midway",
    "Halsted-Midway",
    "Roosevelt/Wabash",
    // Loop (inner track, clockwise)
    "Adams/Wabash",
    "Washington/Wabash",
    "State/Lake",
    "Clark/Lake",
    "Washington/Wells",
    "Quincy/Wells",
    "LaSalle/Van Buren",
    "Library",
  ],

  Pink: [
    "54th/Cermak",
    "Cicero-Douglas",
    "Kostner",
    "Pulaski-Douglas",
    "Central Park",
    "Kedzie-Douglas",
    "California-Douglas",
    "Western-Douglas",
    "Damen",
    "18th",
    "Polk",
    "Ashland-Lake",
    "Morgan",
    "Clinton-Lake",
    // Loop (inner track, clockwise)
    "Clark/Lake",
    "State/Lake",
    "Washington/Wabash",
    "Adams/Wabash",
    "Library",
    "LaSalle/Van Buren",
    "Quincy/Wells",
    "Washington/Wells",
  ],

  // Green Line has two branches south of Garfield
  // We draw the main trunk + each branch as separate segments
  Green: [
    "Harlem-Lake",
    "Oak Park-Lake",
    "Ridgeland",
    "Austin-Lake",
    "Central-Lake",
    "Laramie",
    "Cicero-Lake",
    "Pulaski-Lake",
    "Conservatory-Central Park",
    "Kedzie-Lake",
    "California-Lake",
    "Ashland-Lake",
    "Morgan",
    "Clinton-Lake",
    "Clark/Lake",
    "State/Lake",
    "Washington/Wabash",
    "Adams/Wabash",
    "Roosevelt/Wabash",
    "Cermak-McCormick Place",
    "35-Bronzeville-IIT",
    "Indiana",
    "43rd",
    "47th-South Elevated",
    "51st",
    "Garfield-South Elevated",
    // East fork to Cottage Grove
    "King Drive",
    "Cottage Grove",
  ],
  // Ashland/63rd branch (drawn separately)
  Green_south: [
    "Garfield-South Elevated",
    "Halsted/63rd",
    "Ashland/63rd",
  ],

  Yellow: [
    "Howard",
    "Oakton-Skokie",
    "Dempster-Skokie",
  ],
}
